# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: [--maxkb=600]
  # Check Markdown for relative URLs
  - repo: https://github.com/klieret/jekyll-relative-url-check
    rev: v2.0.1
    hooks:
      - id: jekyll-relative-url-check-markdown
  # Run Prettier
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.5.1
    hooks:
      - id: prettier
  # Convert images in /assets/img/remote to webP
  - repo: local
    hooks:
      - id: generate_webp
        name: "Convert remote images to WebP"
        entry: ./generate_webp.sh
        language: script
